apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paymentgateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paymentgateway.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.containerPort }}"
  DB_URL: {{ .Values.config.dbUrl | quote }}
  ISSUER_URI: {{ .Values.config.issuerUri | quote }}
  {{- if .Values.config.kafkaBootstrapServers }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  {{- end }}
  SPRING_FLYWAY_ENABLED: "false"
