apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "paymentgateway.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paymentgateway.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "paymentgateway.fullname" . }}-secret
    creationPolicy: Owner
  data:
    # DB credentials
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretName }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretName }}
        property: password
    # Razorpay credentials
    - secretKey: RAZORPAY_KEY_ID
      remoteRef:
        key: {{ .Values.externalSecrets.razorpaySecretName }}
        property: key_id
    - secretKey: RAZORPAY_KEY_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.razorpaySecretName }}
        property: key_secret
    - secretKey: RAZORPAY_WEBHOOK_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.razorpaySecretName }}
        property: webhook_secret
